[package]
name = "server_side_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {version = "0.9", features = ["image"] }
iced_aw = "0.5.0"
opencv = "0.79.0"
serialport = "4.2.0"
